name: Daily PP Tests

workflow_dispatch:


jobs:
  job1_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Code
        run: echo "Building..."
  
 # job2_test:
 #   needs: job1_build # This job will ONLY start after job1_build is complete and successful
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Run Tests
 #       run: echo "Testing after build..."