name: Daily PP Tests

on:
  schedule:
    # Run every day at 7:10 AM UTC
    - cron: '30 7 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Code
        run: echo "Building..."
  
  test:
    needs: Build # This job will ONLY start after job1_build is complete and successful
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Testing after build..."