name: Daily PP Tests

on:
  schedule:
    # Run every day at 7:10 AM UTC
    - cron: '30 7 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/* # Use a long-term support Node.js version

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI environments

      - name: Install Playwright Browsers
        # This command installs the necessary browsers (Chromium, Firefox, WebKit)
        run: npx playwright install --with-deps
  
  test:
    needs: Build # This job will ONLY start after job1_build is complete and successful
    runs-on: ubuntu-latest
    steps:
      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # Uploads report even if a test fails
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 # Retains the report artifact for 30 days